quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=@BD2419#lol09
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/RequestFlow

quarkus.hibernate-orm.database.generation=update